#!/usr/bin/env bash

function main() {
    delete_initial_local_variables_file
    delete_conventional_scripts
}

function delete_initial_local_variables_file() {
    eval "$(grep -E '^INITIAL_LOCAL_VARIABLES_[[:alnum:]_]+=.*' ~/.bash_profile)"
    [[ -f "$INITIAL_LOCAL_VARIABLES_PATH" ]] && rm "$INITIAL_LOCAL_VARIABLES_PATH"
}

function delete_conventional_scripts() {
    rm_noerr ~/.bashrc
    rm_noerr ~/.bash_logout
    rm_noerr ~/.bash_profile
}

function rm_noerr() {
    rm "$@" 2> /dev/null
}

main