#!/usr/bin/env bash
if ! command -v __ansi__ &> /dev/null || ! command -v _indent &> /dev/null; then
    echo "__ansi__ or _indent functions unavailable."
    exit 1
fi

if [ "$USER" == "$1" ]; then
	__ansi__ default
	echo -n "($1) "
fi
_indent
