if [[ -v __LOADERS_SLASH_ENVIRONMENT_VARIABLES_SLASH_INITIAL_DOT_SH__ ]]; then
    return 0
fi

unset_on_exit __LOADERS_SLASH_ENVIRONMENT_VARIABLES_SLASH_INITIAL_DOT_SH__
__LOADERS_SLASH_ENVIRONMENT_VARIABLES_SLASH_INITIAL_DOT_SH__="$(get_this_file_name)"
    
SOURCEABLE_EXTENSIONS=("sh" "bash")
EMITTABLE_EXTENSIONS=("py" "js" "ts" "pl" "rb")

unset_on_exit SOURCEABLE_EXTENSIONS
unset_on_exit EMITTABLE_EXTENSIONS

